# import=[
#     "~/.config/alacritty/themes/themes/catppuccin_frappe.toml",
# ]

live_config_reload = true

[env]
WINIT_X11_SCALE_FACTOR = "2.0"

[mouse]
hide_when_typing=true

[font]
normal = { family = "FiraCode Nerd Font", style="Regular" }
